language: java

jdk:
  - openjdk7
  - oraclejdk7  
  - oraclejdk8

before_install: git clone https://github.com/checkstyle/checkstyle.git && cd checkstyle 
  && mvn clean install -Passembly
  && cd ..

install: mvn clean test

